language: cpp
before_install:
  - sudo apt-get -y install freeglut3-dev
  - sudo apt-get -y install cmake
  - sudo apt-get -y install unzip
  - sudo apt-get -y install
  - sudo apt-get install libx11-dev
  - sudo apt-get install xorg-dev
  - sudo apt-get install libudev-dev
install:
  - wget https://github.com/kfrlib/kfr/archive/4.2.0.tar.gz -O kfr-4.2.0.tar.gz
  - tar -xzvf kfr-4.2.0.tar.gz
  - cd kfr-4.2.0
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=ON -DENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-stdlib=libc++ -std=c++17" ..
  - make -j
  - sudo make install -j
  - cd ..
  - cd ..
  - wget https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip -O sfml-source-2.5.zip
  - unzip sfml-source-2.5.zip
  - cd SFML-2.5.1
  - mkdir build
  - cd build
  - cmake ..
  - make -j
  - sudo make install
  - cd ..
  - cd ..
compiler: clang
script: make clean -f Makefile_LINUX && make -j -f Makefile_LINUX
